name: "extract build info"
description: "Read info.yaml and compute build metadata"
outputs:
  org_name:
    description: "org name"
    value: ${{ steps.extract.outputs.org_name }}
  app_name:
    description: "app name"
    value: ${{ steps.extract.outputs.app_name }}
  repo_tag:
    description: "repo tag"
    value: ${{ steps.extract.outputs.repo_tag }}
  app_project:
    description: "app project"
    value: ${{ steps.extract.outputs.app_project }}
  environment:
    description: "environment"
    value: ${{ steps.extract.outputs.environment }}
  repo_url:
    description: "repo url"
    value: ${{ steps.extract.outputs.repo_url }}
  argocd_project_namespace:
    description: "argocd project namespace"
    value: ${{ steps.extract.outputs.argocd_project_namespace }}
  namespace:
    description: "namespace"
    value: ${{ steps.extract.outputs.namespace }}
  tag_exists:
    description: "tag exists"
    value: ${{ steps.extract.outputs.tag_exists }}
  kustomization_path:
    description: "kustomization path"
    value: ${{ steps.extract.outputs.kustomization_path }}
  resource_group:
    description: "resource group"
    value: ${{ steps.extract.outputs.resource_group }}
  cluster_name:
    description: "cluster name"
    value: ${{ steps.extract.outputs.cluster_name }}
  commit_id:
    description: "commit id"
    value: ${{ steps.extract.outputs.commit_id }}
  last_tag_prefix:
    description: "last tag prefix"
    value: ${{ steps.extract.outputs.last_tag_prefix }}
  last_tag:
    description: "last tag"
    value: ${{ steps.extract.outputs.last_tag }}

inputs:
  namespace_override:
    description: "Namespace override"
    required: false
  kustomization_overlay:
    description: "Kustomization overlay"
    required: false
  cluster_develop:
    description: "Develop cluster URL"
    required: false
  cluster_production:
    description: "Production cluster URL"
    required: false
  cluster_prod:
    description: "Prod cluster URL"
    required: false

runs:
  using: "composite"
  steps:
    - name: Extract info
      id: extract
      shell: bash 
      env:
        NAMESPACE_OVERRIDE: ${{ inputs.namespace_override }}
        KUSTOMIZATION_OVERLAY: ${{ inputs.kustomization_overlay }}
        CLUSTER_DEVELOP: ${{ inputs.cluster_develop }}
        CLUSTER_PRODUCTION: ${{ inputs.cluster_production }}
        CLUSTER_PROD: ${{ inputs.cluster_prod }}
      run: $GITHUB_ACTION_PATH/../../../scripts/get-info.sh
