stages:
- stage: git_tag
  displayName: tagging
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: tag_push
    displayName: tag job
    steps:
      - template: /commons/extract_info.yml
        parameters:
          namespace_override: ${{ parameters.namespace_override }}
          archetype: ${{ parameters.archetype }}
          kustomization_overlay: ${{ parameters.kustomization_overlay }}

      - task: DownloadSecureFile@1
        name: private_key_file
        displayName: 'Download private key'
        inputs:
          secureFile: 'azure-devops-key-rsa-sha2-512'

      - bash: |
          # Configure o git na pasta local
          git config user.name "core-pipelines"
          git config user.email "$(Build.RequestedForEmail)"

          chmod 600 $(private_key_file.secureFilePath)

          function tag_info() {        
            commit_message=$(git log --format=%B -n 1 | head -n 1)
            pat="$azp_git_pat"
            environment="$(environment)"
            commit_id=$(git rev-parse --short HEAD)

            echo "##vso[task.setvariable variable=git_tag]$(repo_tag)"
            echo "##vso[task.setvariable variable=commit_message]$commit_message"
            echo "##vso[task.setvariable variable=pat;issecret=true]$pat"
          }
          
          if [[ "$(tag_exists)" == "true" ]]; then
            echo "##vso[task.setvariable variable=disable_tagging]true"
            echo "tag $git_tag já existe..."
            echo "desativando task de tagging..."
          else
            tag_info
          fi

          echo "DEBUG"
          echo "app_name: $(app_name)"
          echo "repo_tag: $(repo_tag)"
          echo "tag_exists: $(tag_exists)"
        condition: succeeded()
        displayName: extract tag details

      - task: Bash@3
        inputs:
          targetType: 'inline'
          workingDirectory: $(Build.Repository.LocalPath)
          script: |
            # Configure git local
            git config user.name "core-pipelines"
            git config user.email "$(Build.RequestedForEmail)"

            chmod 600 $(private_key_file.secureFilePath)
            export GIT_SSH_COMMAND="ssh -i $(private_key_file.secureFilePath) -o StrictHostKeyChecking=no"

            org_name=$(echo "$(System.CollectionUri)" | awk -F/ '{print $4}')
            push_url="git@ssh.dev.azure.com:v3/$org_name/$(System.TeamProject)/$(Build.Repository.Name)"

            echo "git_tag: $(git_tag)"
            echo "commit_message: $(commit_message)"
            echo "org_name: $org_name"
            echo "git log: $(git log --pretty=oneline | head -n 1)"

            # Cria a tag se não existir
            if git tag -l | grep -q "$(git_tag)"; then
              echo "Tag já existe, sobrescrevendo..."
              git tag -f -a "$(git_tag)" -m "$(commit_message)"
              git push -f $push_url "$(git_tag)"
            else
              echo "Criando nova tag"
              git tag -a "$(git_tag)" -m "$(commit_message)"
              git push $push_url "$(git_tag)"
            fi

            rm -rf $(private_key_file.secureFilePath)
        name: push_tag
        condition: and(succeeded(), ne(variables.disable_tagging, 'true'))
        displayName: push tag
