  stages:
  - ${{ if and(eq(parameters.archetype, 'containers'), ne(parameters.docker_options, 'disable_docker')) }}:
    - template: /archetypes/containers/build.yml
      parameters:
        container_registry: ${{ parameters.container_registry }}
        container_repository: ${{ parameters.container_repository }}
        container_tag: ${{ parameters.container_tag }}
        disable_docker_push: ${{ parameters.disable_docker_push }}
        dockerfile: ${{ parameters.dockerfile }}
        docker_options: ${{ parameters.docker_options }}
        namespace_override: ${{ parameters.namespace_override }}
        archetype: ${{ parameters.archetype }}
        kustomization_overlay: ${{ parameters.kustomization_overlay }}

  - template: /commons/tagging.yml
    parameters:
      archetype: ${{ parameters.archetype }}
      kustomization_overlay: ${{ parameters.kustomization_overlay }}
      helm_chart: ${{ parameters.helm_chart }}
      ssh_repo_key: ${{ parameters.ssh_repo_key }}
      namespace_override: ${{ parameters.namespace_override }}
      ${{ if and(eq(parameters.archetype, 'containers'), ne(parameters.docker_options, 'disable_docker')) }}:
        dependsOn: containers_build
      ${{ else }}:
        dependsOn: []

  - template: /archetypes/cd/${{ parameters.gitops_app }}.yml
    parameters:
      namespace_override: ${{ parameters.namespace_override }}
      archetype: ${{ parameters.archetype }}
      kustomization_overlay: ${{ parameters.kustomization_overlay }}
      agent_pool: ${{ parameters.environment }}_pool
      helm_chart: ${{ parameters.helm_chart }}
      ssh_repo_key: ${{ parameters.ssh_repo_key }}